"""message

Revision ID: e612c30870ae
Revises: 
Create Date: 2025-11-02 23:51:13.177200

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e612c30870ae'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('buyers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('national_id', sa.String(length=20), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('gender', sa.String(length=10), nullable=True),
    sa.Column('county_of_residence', sa.Enum('BARINGO', 'BOMET', 'BUNGOMA', 'BUSIA', 'ELGEYO_MARAKWET', 'EMBU', 'GARISSA', 'HOMA_BAY', 'ISIOLO', 'KAJIADO', 'KAKAMEGA', 'KERICHO', 'KIAMBU', 'KILIFI', 'KIRINYAGA', 'KISII', 'KISUMU', 'KITUI', 'KWALE', 'LAIKIPIA', 'LAMU', 'MACHAKOS', 'MAKUENI', 'MANDERA', 'MARSABIT', 'MERU', 'MIGORI', 'MOMBASA', 'MURANG_A', 'NAIROBI', 'NAKURU', 'NANDI', 'NAROK', 'NYAMIRA', 'NYANDARUA', 'NYERI', 'SAMBURU', 'SIAYA', 'TAITA_TAVETA', 'TANA_RIVER', 'THARAKA_NITHI', 'TRANS_NZOIA', 'TURKANA', 'UASIN_GISHU', 'VIHIGA', 'WAJIR', 'WEST_POKOT', name='kenyancounty'), nullable=True),
    sa.Column('marital_status', sa.String(length=20), nullable=True),
    sa.Column('dependents', sa.Integer(), nullable=True),
    sa.Column('employment_status', sa.String(length=20), nullable=True),
    sa.Column('employer_name', sa.String(length=200), nullable=True),
    sa.Column('occupation', sa.String(length=100), nullable=True),
    sa.Column('employment_duration', sa.Integer(), nullable=True),
    sa.Column('monthly_gross_income', sa.Float(), nullable=True),
    sa.Column('monthly_net_income', sa.Float(), nullable=True),
    sa.Column('other_income', sa.Float(), nullable=True),
    sa.Column('has_existing_loans', sa.Boolean(), nullable=True),
    sa.Column('loan_types', sa.String(length=500), nullable=True),
    sa.Column('monthly_loan_repayments', sa.Float(), nullable=True),
    sa.Column('monthly_expenses', sa.Float(), nullable=True),
    sa.Column('credit_score', sa.Integer(), nullable=True),
    sa.Column('preferred_property_type', sa.Enum('APARTMENT', 'BUNGALOW', 'TOWNHOUSE', 'VILLA', name='propertytype'), nullable=True),
    sa.Column('target_county', sa.Enum('BARINGO', 'BOMET', 'BUNGOMA', 'BUSIA', 'ELGEYO_MARAKWET', 'EMBU', 'GARISSA', 'HOMA_BAY', 'ISIOLO', 'KAJIADO', 'KAKAMEGA', 'KERICHO', 'KIAMBU', 'KILIFI', 'KIRINYAGA', 'KISII', 'KISUMU', 'KITUI', 'KWALE', 'LAIKIPIA', 'LAMU', 'MACHAKOS', 'MAKUENI', 'MANDERA', 'MARSABIT', 'MERU', 'MIGORI', 'MOMBASA', 'MURANG_A', 'NAIROBI', 'NAKURU', 'NANDI', 'NAROK', 'NYAMIRA', 'NYANDARUA', 'NYERI', 'SAMBURU', 'SIAYA', 'TAITA_TAVETA', 'TANA_RIVER', 'THARAKA_NITHI', 'TRANS_NZOIA', 'TURKANA', 'UASIN_GISHU', 'VIHIGA', 'WAJIR', 'WEST_POKOT', name='kenyancounty'), nullable=True),
    sa.Column('estimated_property_value', sa.Float(), nullable=True),
    sa.Column('desired_loan_amount', sa.Float(), nullable=True),
    sa.Column('desired_repayment_period', sa.Integer(), nullable=True),
    sa.Column('down_payment_amount', sa.Float(), nullable=True),
    sa.Column('bank_name', sa.String(length=100), nullable=True),
    sa.Column('account_number', sa.String(length=50), nullable=True),
    sa.Column('mpesa_number', sa.String(length=20), nullable=True),
    sa.Column('national_id_uploaded', sa.Boolean(), nullable=True),
    sa.Column('kra_pin_uploaded', sa.Boolean(), nullable=True),
    sa.Column('bank_statement_uploaded', sa.Boolean(), nullable=True),
    sa.Column('credit_report_uploaded', sa.Boolean(), nullable=True),
    sa.Column('proof_of_residence_uploaded', sa.Boolean(), nullable=True),
    sa.Column('profile_complete', sa.Boolean(), nullable=True),
    sa.Column('creditworthiness_score', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('lenders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('institution_name', sa.String(length=200), nullable=False),
    sa.Column('contact_person', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('business_registration_number', sa.String(length=50), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=True),
    sa.Column('logo_url', sa.String(length=255), nullable=True),
    sa.Column('company_type', sa.String(length=50), nullable=True),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('established_year', sa.Integer(), nullable=True),
    sa.Column('license_number', sa.String(length=100), nullable=True),
    sa.Column('street_address', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('county', sa.Enum('BARINGO', 'BOMET', 'BUNGOMA', 'BUSIA', 'ELGEYO_MARAKWET', 'EMBU', 'GARISSA', 'HOMA_BAY', 'ISIOLO', 'KAJIADO', 'KAKAMEGA', 'KERICHO', 'KIAMBU', 'KILIFI', 'KIRINYAGA', 'KISII', 'KISUMU', 'KITUI', 'KWALE', 'LAIKIPIA', 'LAMU', 'MACHAKOS', 'MAKUENI', 'MANDERA', 'MARSABIT', 'MERU', 'MIGORI', 'MOMBASA', 'MURANG_A', 'NAIROBI', 'NAKURU', 'NANDI', 'NAROK', 'NYAMIRA', 'NYANDARUA', 'NYERI', 'SAMBURU', 'SIAYA', 'TAITA_TAVETA', 'TANA_RIVER', 'THARAKA_NITHI', 'TRANS_NZOIA', 'TURKANA', 'UASIN_GISHU', 'VIHIGA', 'WAJIR', 'WEST_POKOT', name='kenyancounty'), nullable=True),
    sa.Column('postal_code', sa.String(length=20), nullable=True),
    sa.Column('secondary_phone', sa.String(length=20), nullable=True),
    sa.Column('fax_number', sa.String(length=20), nullable=True),
    sa.Column('customer_service_email', sa.String(length=120), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('services_offered', sa.JSON(), nullable=True),
    sa.Column('operating_hours', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'LENDER', 'HOMEBUYER', name='userrole'), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('feedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('buyer_id', sa.Integer(), nullable=True),
    sa.Column('lender_id', sa.Integer(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['buyer_id'], ['buyers.id'], ),
    sa.ForeignKeyConstraint(['lender_id'], ['lenders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lender_analytics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lender_id', sa.Integer(), nullable=False),
    sa.Column('total_loans_disbursed', sa.Integer(), nullable=True),
    sa.Column('total_amount_issued', sa.Float(), nullable=True),
    sa.Column('active_loans', sa.Integer(), nullable=True),
    sa.Column('revenue_from_interest', sa.Float(), nullable=True),
    sa.Column('default_rate', sa.Float(), nullable=True),
    sa.Column('generated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['lender_id'], ['lenders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mortgage_listings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lender_id', sa.Integer(), nullable=False),
    sa.Column('property_title', sa.String(length=200), nullable=False),
    sa.Column('property_type', sa.Enum('APARTMENT', 'BUNGALOW', 'TOWNHOUSE', 'VILLA', name='propertytype'), nullable=False),
    sa.Column('bedrooms', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('county', sa.Enum('BARINGO', 'BOMET', 'BUNGOMA', 'BUSIA', 'ELGEYO_MARAKWET', 'EMBU', 'GARISSA', 'HOMA_BAY', 'ISIOLO', 'KAJIADO', 'KAKAMEGA', 'KERICHO', 'KIAMBU', 'KILIFI', 'KIRINYAGA', 'KISII', 'KISUMU', 'KITUI', 'KWALE', 'LAIKIPIA', 'LAMU', 'MACHAKOS', 'MAKUENI', 'MANDERA', 'MARSABIT', 'MERU', 'MIGORI', 'MOMBASA', 'MURANG_A', 'NAIROBI', 'NAKURU', 'NANDI', 'NAROK', 'NYAMIRA', 'NYANDARUA', 'NYERI', 'SAMBURU', 'SIAYA', 'TAITA_TAVETA', 'TANA_RIVER', 'THARAKA_NITHI', 'TRANS_NZOIA', 'TURKANA', 'UASIN_GISHU', 'VIHIGA', 'WAJIR', 'WEST_POKOT', name='kenyancounty'), nullable=False),
    sa.Column('price_range', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('interest_rate', sa.Float(), nullable=False),
    sa.Column('repayment_period', sa.Integer(), nullable=False),
    sa.Column('down_payment', sa.Float(), nullable=False),
    sa.Column('monthly_payment', sa.Float(), nullable=True),
    sa.Column('eligibility_criteria', sa.Text(), nullable=True),
    sa.Column('images', sa.JSON(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'ACQUIRED', 'SOLD', name='listingstatus'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['lender_id'], ['lenders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pre_approvals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('buyer_id', sa.Integer(), nullable=False),
    sa.Column('lender_id', sa.Integer(), nullable=False),
    sa.Column('approved_amount', sa.Float(), nullable=False),
    sa.Column('interest_rate', sa.Float(), nullable=False),
    sa.Column('valid_until', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'NEEDS_INFO', name='applicationstatus'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['buyer_id'], ['buyers.id'], ),
    sa.ForeignKeyConstraint(['lender_id'], ['lenders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mortgage_applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('borrower_id', sa.Integer(), nullable=False),
    sa.Column('lender_id', sa.Integer(), nullable=False),
    sa.Column('listing_id', sa.Integer(), nullable=False),
    sa.Column('requested_amount', sa.Float(), nullable=False),
    sa.Column('repayment_years', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'NEEDS_INFO', name='applicationstatus'), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['lender_id'], ['lenders.id'], ),
    sa.ForeignKeyConstraint(['listing_id'], ['mortgage_listings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('saved_properties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('buyer_id', sa.Integer(), nullable=False),
    sa.Column('listing_id', sa.Integer(), nullable=False),
    sa.Column('saved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['buyer_id'], ['buyers.id'], ),
    sa.ForeignKeyConstraint(['listing_id'], ['mortgage_listings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('active_mortgages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('borrower_id', sa.Integer(), nullable=False),
    sa.Column('lender_id', sa.Integer(), nullable=False),
    sa.Column('principal_amount', sa.Float(), nullable=False),
    sa.Column('interest_rate', sa.Float(), nullable=False),
    sa.Column('repayment_term', sa.Integer(), nullable=False),
    sa.Column('next_payment_due', sa.Date(), nullable=True),
    sa.Column('remaining_balance', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'COMPLETED', 'DEFAULTED', 'REFINANCED', name='mortgagestatus'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['mortgage_applications.id'], ),
    sa.ForeignKeyConstraint(['lender_id'], ['lenders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payment_schedules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mortgage_id', sa.Integer(), nullable=False),
    sa.Column('payment_date', sa.Date(), nullable=False),
    sa.Column('amount_due', sa.Float(), nullable=False),
    sa.Column('amount_paid', sa.Float(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'PAID', 'LATE', 'MISSED', name='paymentstatus'), nullable=True),
    sa.Column('receipt_url', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['mortgage_id'], ['active_mortgages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('refinancing_offers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lender_id', sa.Integer(), nullable=False),
    sa.Column('mortgage_id', sa.Integer(), nullable=False),
    sa.Column('new_interest_rate', sa.Float(), nullable=False),
    sa.Column('new_term', sa.Integer(), nullable=False),
    sa.Column('offer_expiry', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('OFFERED', 'ACCEPTED', 'DECLINED', 'EXPIRED', name='offerstatus'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['lender_id'], ['lenders.id'], ),
    sa.ForeignKeyConstraint(['mortgage_id'], ['active_mortgages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('refinancing_offers')
    op.drop_table('payment_schedules')
    op.drop_table('active_mortgages')
    op.drop_table('saved_properties')
    op.drop_table('mortgage_applications')
    op.drop_table('pre_approvals')
    op.drop_table('mortgage_listings')
    op.drop_table('lender_analytics')
    op.drop_table('feedback')
    op.drop_table('users')
    op.drop_table('lenders')
    op.drop_table('buyers')
    op.drop_table('admins')
    # ### end Alembic commands ###
